version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  backend:
    build: ./server
    command: npm run dev
    volumes:
      - ./backend:/backend/
    ports:
      - "4040:4040"
    links:
      - mongo
    environment:
     - MONGO_URI=mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
      - redis
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
  client:
    build: ./client
    command: npm run dev
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
      
 
